Added fixtures
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #17
Opened 2018-04-27 19:19 UTC by viLLoyd

2018-04-27 20:46 UTC, gregurco requested changes

2018-04-27 20:46 UTC, gregurco commented on src/DataFixtures/JobFixtures.php
> +            $job->setType($faker->shuffleArray(['private', 'public'])[0]);
use `$faker->randomElement()`

2018-04-27 20:46 UTC, gregurco commented on src/DataFixtures/JobFixtures.php
> +            $job->setPublic($faker->shuffleArray([true, false])[0]);
also randomElement

2018-04-27 20:46 UTC, gregurco commented on src/Entity/Affiliate.php
> +    public function setTimestamp(): void
better to name this method as the action when it's triggered: `public function prePersist(): void`

2018-04-27 20:46 UTC, gregurco commented on src/Entity/Affiliate.php
> +    public function setTimestamp(): void
and in this case method will not look like setter

2018-04-27 20:46 UTC, gregurco commented on src/Traits/Timestamps.php
> +trait Timestamps
if it's trait, then better add suffix Trait: `trait TimestampsTrait`

2018-04-28 01:30 UTC, viLLoyd commented
Added adjustments

2018-04-28 13:15 UTC, gregurco requested changes

2018-04-28 13:15 UTC, gregurco commented on src/DataFixtures/AffiliateFixtures.php
> +        return array(
use `[]` instead of `array()`

2018-04-28 13:15 UTC, gregurco commented on src/DataFixtures/JobFixtures.php
> +        return array(
also `[]` array

2018-04-28 21:42 UTC, merged