Relations, life cycle callbacks, fixtures
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #18
Opened 2018-04-27 20:56 UTC by gconstantin

2018-04-27 21:31 UTC, gregurco commented on src/Entity/Affiliate.php
> +        $this->createdAt = new \DateTime('now', new\DateTimeZone('UTC'));
usually timezone is setup on the level of php config. No need to use second param. Also the first one is default. You can write simply: `$this->createdAt = new \DateTime();`

2018-04-27 21:31 UTC, gregurco commented on src/Repository/AffiliateRepository.php
> +class AffiliateRepository extends EntityRepository
see here how repository should looks like: https://symfony.com/doc/current/doctrine.html#querying-for-objects-the-repository
You did in in sf 3.3 style.

2018-04-28 06:01 UTC, gconstantin commented
Added changes

2018-04-28 13:19 UTC, gregurco requested changes

2018-04-28 13:19 UTC, gregurco commented on src/DataFixtures/CategoryFixtures.php
> +        return CategoryFixtures::REFERENCE.$id;
code style fix, should be:
`return CategoryFixtures::REFERENCE . $id;`

2018-04-28 13:19 UTC, gregurco commented on src/DataFixtures/CategoryFixtures.php
> +use Faker\Factory;
import `use Faker;` and use it as `$faker = Faker\Factory::create();`

2018-04-29 08:03 UTC, gconstantin commented
Fixed

2018-04-29 08:12 UTC, gregurco commented
@gconstantin :+1:

2018-04-29 08:12 UTC, merged