Day 3. Homerowk
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #19
Opened 2018-04-28 06:37 UTC by ksardedik

- Entities' relations (+ "add", "remove", "get" methods)
- Lifecycle callbacks
- Migrations
- Fixtures (+ dependencies)
- Faker

2018-04-28 13:25 UTC, gregurco requested changes

2018-04-28 13:25 UTC, gregurco commented on src/DataFixtures/AffiliateFixtures.php
> +            $affiliate->setToken($faker->password(6,6));
code style fix, should be:
`$faker->password(6, 6)`
(space after **,**)

2018-04-28 13:25 UTC, gregurco commented on src/DataFixtures/AffiliateFixtures.php
> +            $affiliate->addCategory($this->getReference('category_'.$i));
also code style fix (space before and after **.**):
`$this->getReference('category_' . $i)`

2018-04-28 13:25 UTC, gregurco commented on src/DataFixtures/AffiliateFixtures.php
> +        return array(
use `[]` instead of `array()`

2018-04-28 13:25 UTC, gregurco commented on src/DataFixtures/CategoryFixtures.php
> +        for ($i = 0; $i < 10; $i++) {
add new empty line before `for`. It will do code more readable

2018-04-28 13:25 UTC, gregurco commented on src/DataFixtures/CategoryFixtures.php
> +            $this->addReference('category_'.$i, $category);
also code style

2018-04-28 13:25 UTC, gregurco commented on src/Entity/Affiliate.php
> +        $this->categories->add($category);
better to check if element if not already added:
```
if (!$this->categories->contains($category)) {
    $this->categories->add($category);
}
```

2018-04-29 13:31 UTC, ksardedik commented
Fixed

2018-04-29 14:30 UTC, gregurco requested changes

2018-04-29 14:30 UTC, gregurco commented on src/Entity/Affiliate.php
> +        if(!$this->categories->contains($category))
code style:
```
if (!$this->categories->contains($category)) {
    $this->categories->add($category);
}
```

2018-04-29 14:30 UTC, gregurco commented on src/Entity/Category.php
> +        if(!$this->jobs->contains($job))
also code style

2018-04-29 15:17 UTC, ksardedik commented
Fixed

2018-04-29 15:21 UTC, merged