HW-day4
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #21
Opened 2018-04-28 19:45 UTC by Vlad6847

2018-04-29 21:05 UTC, gregurco requested changes

2018-04-29 21:05 UTC, gregurco commented on src/Controller/JobController.php
> +     * @Route("/orderby/{slug}", name="orderBy")
try to do order by not in separate action but in `listAction`. You can define order by field as optional request param.

2018-04-29 21:05 UTC, gregurco commented on src/Repository/JobRepository.php
>          return $this->createQueryBuilder('a')
change alias. Usually it's first letter of the entity. In your case better to write:
`return $this->createQueryBuilder('j')`

2018-04-29 21:05 UTC, gregurco commented on src/Repository/JobRepository.php
> +                    ->orderBy('a.'.$field, 'ASC')
it's not good idea to insert the field name in this way... you don't validate it and etc.

2018-04-29 21:05 UTC, gregurco commented on src/Repository/JobRepository.php
> +    public function searchPosition($field)
do you use this method?

2018-04-29 21:05 UTC, gregurco commented on templates/job/list.html.twig
> +        <th class="text-center"><a href="{{ url('job.list') }}orderby/location">City</a></th>
code style:
```
<tr class="active">
    <th class="text-center">
        <a href="{{ url('job.list') }}orderby/location">City</a>
    </th>
...
```

2018-04-29 21:05 UTC, gregurco commented on templates/job/list.html.twig
> +                {% if job.activated %}
it's better to get activated jobs on level of sql query and not to filter them in view.

2018-04-30 14:23 UTC, gregurco requested changes

2018-04-30 14:23 UTC, gregurco commented on src/Controller/JobController.php
> +        $request   = new Request($_GET);
1. don't align rows in `=` sign
2. don't initialize request object, use it like written here: https://symfony.com/doc/current/controller.html#the-request-object-as-a-controller-argument

2018-04-30 14:23 UTC, gregurco commented on templates/job/list.html.twig
> +            <th class="text-center"><a href="{{ url('job.list') }}?sort_by=location&order=ASC">City</a></th>
https://symfony.com/doc/current/reference/twig_reference.html#url - there is written that the second parameter in `url` is `parameters`. So, add them as second parameter and not as concatenation

2018-05-01 06:09 UTC, gregurco requested changes

2018-05-01 06:09 UTC, gregurco commented on src/Controller/JobController.php
> +    public function search(Request $request): Response
do you use this method?

2018-05-01 06:09 UTC, gregurco commented on src/Repository/JobRepository.php
> +                    ->andWhere('j.position like '.$position.'%')
don't use query parameters in this way, read https://symfony.com/doc/current/doctrine.html#querying-for-objects-the-repository especially method `setParameter`

2018-05-01 06:09 UTC, gregurco commented on templates/job/list.html.twig
> +            <th class="text-center"><a href="{{ url('job.list', ['location', 'ASC']) }}">City</a></th>
better to write: `{{ url('job.list', {field: 'location', direction: 'ASC'}) }}` - then you will have possibility to insert many parameters and to get them by get.
And instead of `$request->query->get('0')` use `$request->query->get('field')`

2018-05-01 10:05 UTC, Vlad6847 commented
done

2018-05-01 14:26 UTC, merged