Controllers, Views, Fixtures
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #23
Opened 2018-04-29 23:24 UTC by sergiu17

2018-04-30 08:26 UTC, gregurco requested changes

2018-04-30 08:26 UTC, gregurco commented on src/Controller/JobsController.php
> +        return $this->render('jobs/index.html.twig', compact('jobs', 'categories'));
you don't have `categories` variable here. Don't use it in `compact` function

2018-04-30 08:26 UTC, gregurco commented on src/Controller/JobsController.php
> +        $categorie = $this->getDoctrine()->getRepository(Category::class)->findOneBy(['id' => $id]);
typo in variable name: `category`

2018-04-30 08:26 UTC, gregurco commented on src/Controller/JobsController.php
> +        $categorie = $this->getDoctrine()->getRepository(Category::class)->findOneBy(['id' => $id]);
If you want to find by id, you can use method `find($id)` instead of `findOneBy`

2018-04-30 08:26 UTC, gregurco commented on src/Controller/JobsController.php
> +        return $this->render('jobs/show.html.twig', compact('job', 'categories'));
you also don't have `categories` variable

2018-04-30 08:26 UTC, gregurco commented on src/DataFixtures/AppFixtures.php
> +        for ( $i = 1; $i <= 10; $i++ ):
use `for () {}` statement

2018-04-30 08:26 UTC, gregurco commented on src/DataFixtures/AppFixtures.php
> +        for ($i = 1; $i <= 10; $i++):
use two fixtures classes instead of one

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Affiliate.php
> +    public function setCategories($categories): void
for collections we don't create `set` method. We create `add` and `remove` methods. See example here: https://github.com/P5CHI-Web-Academy/Homework-Symfony-Symfony/pull/16/files#diff-5bf699e7f399c9468d271dc6b704b315R171

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Category.php
> +            if ($job->getCategoryId() === $this) {
remove this `if`

2018-04-30 08:26 UTC, gregurco commented on templates/partials/nav.html.twig
> +                    {% for category in jobeet.categories %}
it's not good practice to create service, to do it as global twig variable and to call it from templates, especially if it does requests to db.

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Job.php
> +    private $how_to_apply;
camelCase

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Job.php
> +    private $expires_at;
also camel case. Review all properties

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Job.php
> +    public function getCategoryId(): ?Category
`getCategory`

2018-04-30 08:26 UTC, gregurco commented on src/Entity/Job.php
> +    public function setCategoryId(?Category $category): self
`setCategory`

2018-05-01 06:17 UTC, gregurco requested changes

2018-05-01 06:17 UTC, gregurco commented on src/Controller/JobsController.php
> +        return $this->render('jobs/index.html.twig', compact('jobs', 'category', 'categories'));
do you use category and categories variables in `jobs/index.html.twig`? I don't see usage and probably it's better to remove them from controller.

2018-05-01 23:51 UTC, sergiu17 commented on src/Controller/JobsController.php
> +        return $this->render('jobs/index.html.twig', compact('jobs', 'category', 'categories'));
I've removed `category` form `compact` function, but I can't remove `categories` because I use them in `partials/nav.html.twig`. `base.html.twig` includes `partials/nav.html.twig`, and `jobs/index.html.twig` extends base.html.twig`. This is why I did first time with global variables.

2018-05-02 06:17 UTC, gregurco commented on src/Controller/JobsController.php
> +        return $this->render('jobs/index.html.twig', compact('jobs', 'category', 'categories'));
ok :+1:

2018-05-02 06:18 UTC, merged