Day 5. Homework
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #31
Opened 2018-05-04 17:38 UTC by ksardedik

+ Controller upgrades
+ Template upgrades
+ Entity upgrades
+ Repository

2018-05-04 20:59 UTC, gregurco requested changes

2018-05-04 20:59 UTC, gregurco commented on src/DataFixtures/JobFixtures.php
> +            $job->setExpiresAt($faker->dateTimeBetween($startDate = '-20 days', $endDate = '+20 days'));
no need to write in this way and to introduce 2 more variables, just write:
```
$job->setExpiresAt($faker->dateTimeBetween('-20 days', '+20 days'));
```

2018-05-04 20:59 UTC, gregurco commented on src/Repository/JobRepository.php
> +class JobRepository extends EntityRepository
you created repository in SF3 way. See how it should be in SF4:
https://symfony.com/doc/current/doctrine.html#querying-for-objects-the-repository

2018-05-04 20:59 UTC, gregurco commented on src/Repository/JobRepository.php
> +                'activated' => true
add `,` at the last element in array too

2018-05-05 06:25 UTC, ksardedik commented
Fixed

2018-05-05 12:02 UTC, merged