Day 6. Homework
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #33
Opened 2018-05-07 15:39 UTC by ksardedik

The following points have been implemented (+ some improvements):
➢ On list jobs page show only active jobs grouped by category
➢ Show only 10 jobs per category on this page
➢ Expired jobs should not be accessible by link
➢ Install StofDoctrineExtensionsBundle and setup slug for category
(don’t forget about migration)
➢ Create action with route /category/{slug} where will be displayed
all jobs by specific category
➢ Link this page with the page with all categories

2018-05-07 20:46 UTC, gregurco requested changes

2018-05-07 20:46 UTC, gregurco commented on config/packages/twig.yaml
> +    globals:
notice that in all yaml files you have 4 spaces on one level, so finally you should have:
```
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        jobs_show_limit_main_page: 10
```
add 2 more spaces before  `jobs_show_limit_main_page`

2018-05-07 20:46 UTC, gregurco commented on config/packages/twig.yaml
> +    globals:
also fix spaces in `config/packages/stof_doctrine_extensions.yaml`

2018-05-07 20:46 UTC, gregurco commented on src/Controller/CategoryController.php
> +     * @Route("/category/{slug}", name="category_job_list")
don't repeat `category` word in route name here. Finally you will have `category.category_job_list`, better to be `category.job_list`

2018-05-07 20:46 UTC, gregurco commented on src/Controller/CategoryController.php
> +            'jobs' => $category->getJobs(),
in twig you will have category object with jobs two, why do you need to separate them in two variables and to send in twig job with categories and categories?

2018-05-07 20:46 UTC, gregurco commented on src/Controller/JobController.php
> +           'categories' => $categories
add `,` at last element in array

2018-05-07 20:46 UTC, gregurco commented on src/Entity/Job.php
> +        if(!$this->expiresAt){
code style: add space before if: 
```php
if (condition) {
    // ...
}
```

2018-05-07 20:46 UTC, gregurco commented on templates/job/list.html.twig
> +                    <a href="{{ url('category.category_job_list', {slug: category.getSlug()}) }}">{{ category.getName() }}</a>
better `category.slug`

2018-05-08 10:31 UTC, ksardedik commented on src/Controller/CategoryController.php
> +            'jobs' => $category->getJobs(),
It's for page name in "title' block. I will update this, so only category name will be passed to the template, instead of whole object.

2018-05-08 10:52 UTC, ksardedik commented
Fixed

2018-05-08 11:39 UTC, merged