Day 7. Homework
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #38
Opened 2018-05-09 17:26 UTC by ksardedik

The following(+ minor improvements) has been implemented:
➢ Paginate jobs on /category/{slug} page
➢ Show 20 jobs per page

2018-05-09 20:22 UTC, gregurco requested changes

2018-05-09 20:22 UTC, gregurco commented on src/Repository/JobRepository.php
> +            ->andWhere('j.category = :category')
jobs should be only active

2018-05-09 20:22 UTC, gregurco commented on src/Controller/CategoryController.php
> +     * @Route("/category/{slug}/{page}", name="job_list", defaults={"page": 1})
add requirements for `page`

2018-05-10 17:06 UTC, ksardedik commented
Done

2018-05-10 17:35 UTC, merged