Day 7 (pagination and create)
P5CHI-Web-Academy/Homework-Symfony-Symfony pull request #43
Opened 2018-05-11 13:20 UTC by vdumbrav

2018-05-11 13:44 UTC, gregurco requested changes

2018-05-11 13:44 UTC, gregurco commented on src/Controller/CategoryController.php
> +     * @Route("/{slug}/{page}", name="category.show", defaults={"page":1})
add requirements for page. Only number.

2018-05-11 13:44 UTC, gregurco commented on src/Controller/CategoryController.php
> +    ): Response
sing PSR it should be:
```
): Response {
```

https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#45-method-and-function-arguments

2018-05-11 13:44 UTC, gregurco commented on src/Controller/CategoryController.php
> +            'activeJobs' => $activeJobs
add `,` at the last element in array

2018-05-11 13:44 UTC, gregurco commented on src/Repository/JobRepository.php
> +    public function getPaginatedActiveJobsByCategoryQuery(Category $category): AbstractQuery
add PhpDoc for this method

2018-05-11 13:44 UTC, gregurco commented on src/Repository/JobRepository.php
> +                'activated' => true
also `,` at last element

2018-05-11 13:53 UTC, vdumbrav commented
@gregurco fixed.

2018-05-11 20:14 UTC, gregurco requested changes

2018-05-11 20:14 UTC, gregurco commented on src/Controller/CategoryController.php
> +     * @Route("/{slug}/{page}", name="category.show", defaults={"page":1}, requirements={"id" = "\d+"})
`requirements={"page" = "\d+"}` - not id, page

2018-05-11 20:14 UTC, gregurco commented on src/Controller/JobController.php
> +    public function createAction(Request $request, EntityManagerInterface $em): Response
I see that you don't use `Action` in methods.. remove it

2018-05-11 20:14 UTC, gregurco commented on src/Controller/JobController.php
> +            'form' => $form->createView()
add `,` at last element in array

2018-05-11 20:14 UTC, gregurco commented on src/Form/JobType.php
> +                    new Email()
also `,`

2018-05-11 20:14 UTC, gregurco commented on templates/job/create.html.twig
> +        {{ form_end(form) }}</div>
template style:
```
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Job creation</h1>

        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            {{ form_widget(form) }}

            <div class="form-group">
                <button type="submit" class="btn btn-default">Create</button>
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}
```

2018-05-14 13:36 UTC, gregurco requested changes

2018-05-14 13:36 UTC, gregurco commented on src/Controller/CategoryController.php
> +        return $this->render('category/show.html.twig', array(
use `[]` instead of `array()`

2018-05-14 13:39 UTC, vdumbrav commented
@gregurco fixed

2018-05-15 06:15 UTC, merged